spring.application.name=ilcs
spring.ai.openai.api-key=${OPENAI_API_KEY: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}
spring.ai.openai.chat.options.model=openai/gpt-oss-120b
spring.ai.openai.base-url: https://api.groq.com/openai
spring.datasource.url=jdbc:h2:mem:agentdb
server.port=9093
spring.h2.console.enabled=true
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
spring.ai.mistalai.chat.enabled=false
spring.ai.mistralai.api-key=${MISTRAL_API_KEY:v2Z9o0NQdtlmXCYGI93k1vBmjgpo8cl9}
spring.ai.mistralai.embedding.options.model=mistral-embed

